name: lint-test

on:
  push:
    branches: [main]
  pull_request:
    
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set Up
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
        id: go

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2

      - name: Run golangci-lint
        run: golangci-lint run ./... -v

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set Up
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
        id: go

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test ./... -v

